#!/usr/bin/env node

/**
 * Sync README from packages/evalla to root (exact copy)
 * Also generates an Astro component with pre-rendered HTML for the web page
 */

const fs = require('fs');
const path = require('path');
const { marked } = require('marked');

const ROOT_DIR = path.join(__dirname, '..');
const EVALLA_README = path.join(ROOT_DIR, 'packages/evalla/README.md');
const ROOT_README = path.join(ROOT_DIR, 'README.md');
const COMPONENT_OUTPUT = path.join(ROOT_DIR, 'packages/playground/src/components/ReadmeContent.astro');

// Sections to exclude from web page (GitHub-only content)
const SECTIONS_TO_EXCLUDE = [
  'Live Demo'
];

function filterReadmeForWeb(readmeContent) {
  // Remove the Live Demo link line for the web page
  const lines = readmeContent.split('\n');
  const filteredLines = [];

  for (const line of lines) {
    // Skip the Live Demo link line
    if (line.startsWith('[Live Demo]')) {
      continue;
    }
    
    filteredLines.push(line);
  }

  return filteredLines.join('\n');
}

async function generateAstroComponent(readmeContent) {
  console.log('📝 Generating Astro component with pre-rendered HTML...');
  
  // Filter out GitHub-only sections
  const filteredContent = filterReadmeForWeb(readmeContent);
  
  // Convert markdown to HTML
  const htmlContent = await marked(filteredContent);
  
  // Generate Astro component
  // Escape special characters: backslash first, then backticks and dollar signs
  const escapedHtml = htmlContent
    .replace(/\\/g, '\\\\')  // Escape backslashes first
    .replace(/`/g, '\\`')     // Escape backticks
    .replace(/\$/g, '\\$');   // Escape dollar signs
  
  const astroComponent = `<!-- Auto-generated by sync-readme.js - DO NOT EDIT MANUALLY -->
<div class="content" set:html={\`${escapedHtml}\`} />
`;
  
  // Ensure components directory exists
  const componentsDir = path.dirname(COMPONENT_OUTPUT);
  if (!fs.existsSync(componentsDir)) {
    fs.mkdirSync(componentsDir, { recursive: true });
  }
  
  // Write component file
  fs.writeFileSync(COMPONENT_OUTPUT, astroComponent, 'utf-8');
  console.log(`✅ Component generated: ${COMPONENT_OUTPUT}`);
}

function syncReadme() {
  console.log('🔄 Syncing README from packages/evalla to root...');

  // Read the master README from packages/evalla
  const evallaReadme = fs.readFileSync(EVALLA_README, 'utf-8');

  // Write exact copy to root README (no mutation)
  fs.writeFileSync(ROOT_README, evallaReadme, 'utf-8');
  
  console.log('✅ README synced successfully!');
  console.log(`   Source: ${EVALLA_README}`);
  console.log(`   Target: ${ROOT_README}`);
  
  // Return the content for component generation
  return evallaReadme;
}

// Run the sync
async function main() {
  const readmeContent = syncReadme();
  await generateAstroComponent(readmeContent);
  console.log('🎉 All done!');
}

main().catch(error => {
  console.error('Error:', error);
  process.exit(1);
});
