/**
 * Error message enum - used as error messages throughout evalla
 * 
 * These enum values are the actual error messages thrown by the library.
 * For human-readable translations, use formatErrorMessage() function.
 */
export enum ErrorMessage {
  // Validation errors
  INPUT_MUST_BE_ARRAY = 'INPUT_MUST_BE_ARRAY',
  INPUT_MUST_BE_OBJECT = 'INPUT_MUST_BE_OBJECT',
  INPUT_NAME_REQUIRED = 'INPUT_NAME_REQUIRED',
  INPUT_EXPR_OR_VALUE_REQUIRED = 'INPUT_EXPR_OR_VALUE_REQUIRED',
  INPUT_EXPR_MUST_BE_STRING = 'INPUT_EXPR_MUST_BE_STRING',
  DUPLICATE_NAME = 'DUPLICATE_NAME',
  
  // Variable name validation errors
  VARIABLE_NAME_MUST_BE_STRING = 'VARIABLE_NAME_MUST_BE_STRING',
  VARIABLE_NAME_EMPTY = 'VARIABLE_NAME_EMPTY',
  VARIABLE_NAME_WHITESPACE = 'VARIABLE_NAME_WHITESPACE',
  VARIABLE_NAME_DOLLAR_PREFIX = 'VARIABLE_NAME_DOLLAR_PREFIX',
  VARIABLE_NAME_DOUBLE_UNDERSCORE = 'VARIABLE_NAME_DOUBLE_UNDERSCORE',
  VARIABLE_NAME_RESERVED = 'VARIABLE_NAME_RESERVED',
  VARIABLE_NAME_STARTS_WITH_NUMBER = 'VARIABLE_NAME_STARTS_WITH_NUMBER',
  VARIABLE_NAME_CONTAINS_DOT = 'VARIABLE_NAME_CONTAINS_DOT',
  VARIABLE_NAME_INVALID_CHARS = 'VARIABLE_NAME_INVALID_CHARS',
  
  // Parse errors
  PARSE_ERROR = 'PARSE_ERROR',
  PARSE_ERROR_AT_LOCATION = 'PARSE_ERROR_AT_LOCATION',
  PARSE_ERROR_FOR_VARIABLE = 'PARSE_ERROR_FOR_VARIABLE',
  
  // Evaluation errors
  UNDEFINED_VARIABLE = 'UNDEFINED_VARIABLE',
  CANNOT_ACCESS_PROPERTY = 'CANNOT_ACCESS_PROPERTY',
  CALLEE_NOT_FUNCTION = 'CALLEE_NOT_FUNCTION',
  UNSUPPORTED_LOGICAL_OPERATOR = 'UNSUPPORTED_LOGICAL_OPERATOR',
  UNSUPPORTED_NODE_TYPE = 'UNSUPPORTED_NODE_TYPE',
  UNSUPPORTED_BINARY_OPERATOR = 'UNSUPPORTED_BINARY_OPERATOR',
  UNSUPPORTED_UNARY_OPERATOR = 'UNSUPPORTED_UNARY_OPERATOR',
  NO_AST_FOUND = 'NO_AST_FOUND',
  FAILED_TO_EVALUATE = 'FAILED_TO_EVALUATE',
  
  // Type errors
  NAMESPACE_HEAD_AS_VALUE = 'NAMESPACE_HEAD_AS_VALUE',
  NAMESPACE_HEAD_IN_OPERATION = 'NAMESPACE_HEAD_IN_OPERATION',
  EXPRESSION_CANNOT_RETURN_ARRAY = 'EXPRESSION_CANNOT_RETURN_ARRAY',
  EXPRESSION_CANNOT_RETURN_OBJECT = 'EXPRESSION_CANNOT_RETURN_OBJECT',
  EXPRESSION_CANNOT_RETURN_STRING = 'EXPRESSION_CANNOT_RETURN_STRING',
  UNSUPPORTED_RESULT_TYPE = 'UNSUPPORTED_RESULT_TYPE',
  STRING_IN_OPERATION = 'STRING_IN_OPERATION',
  OBJECT_IN_OPERATION = 'OBJECT_IN_OPERATION',
  ARRAY_IN_OPERATION = 'ARRAY_IN_OPERATION',
  STRING_WITH_UNARY = 'STRING_WITH_UNARY',
  OBJECT_WITH_UNARY = 'OBJECT_WITH_UNARY',
  ARRAY_WITH_UNARY = 'ARRAY_WITH_UNARY',
  
  // Security errors
  PROPERTY_ACCESS_DENIED = 'PROPERTY_ACCESS_DENIED',
  FUNCTION_ALIASING_DENIED = 'FUNCTION_ALIASING_DENIED',
  
  // Circular dependency
  CIRCULAR_DEPENDENCY = 'CIRCULAR_DEPENDENCY',
  
  // Format errors
  DECIMAL_PLACES_INVALID = 'DECIMAL_PLACES_INVALID',
  
  // Syntax errors
  EXPRESSION_MUST_BE_STRING = 'EXPRESSION_MUST_BE_STRING',
  EXPRESSION_EMPTY = 'EXPRESSION_EMPTY',
  
  // Internationalization errors
  UNSUPPORTED_LANGUAGE = 'UNSUPPORTED_LANGUAGE',
}
